name: api_credential_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

publish_to: none

dependencies:
  http: ^0.13.5
  http_interceptor: ^1.0.0
  credential_repository:
    path: ../credential_repository

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
